
* Problems we have with workflow

** ShellTask is "sh" task 
   See [[https://github.com/jenkinsci/durable-task-plugin/blob/master/src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java][durabletasks's BourneShellScript.java]] which is utilized by
   [[https://github.com/jenkinsci/workflow-plugin/blob/d6f4a22e0660bce076f733c6c78f3613ef690c50/durable-task-step/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep.java#L50][workflow's ShellStep.java]]. 

   We need to see if we can make a clean translation to window's batch
   calling capabilities.

** Workflow script may cause the build to hang
   We had a call like sh "./script_blah.sh $(($RANDOM%2))" which was
   interpreted to be an interpolation. Groovy threw an exception and
   the job was kept running and was not able to be cancelled. These
   failures disappear from the build history upon restarting Jenkins.

** Workspace is not cleaned on subsequent executions
   If files are created between builds, the files remain (see
   trial-one, script1.sh). The directory reflects the presence of a
   "build file" that should be cleaned up.

*** Can git be cached + =git clean= or something similar

* Questions we have


** Can we integrate and resolve steps from external gradle build files?

** How do we approach loading external files from a repo to form parts of the WF?





